name: ToDo

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0
